client_id: cl1
client_name: Client1
source_db:
  driver: '{ODBC Driver 17 for SQL Server}'
  server: DESKTOP-AGUMSPH
  database: DATABASE
  trusted_connection: 'yes'
  connection_timeout: 30
snowflake:
  account: your_snowflake_account
  user: USER
  password: your_password_account
  warehouse: COMPUTE_WH
  database: BEE_CENTER
  schema: CLIENT1
  role: ACCOUNTADMIN
etl:
  chunk_size: 100000
  create_or_replace: false
  date_format: '%Y-%m-%d'
  max_workers: 8
etl_flow: ../../Flows/ETL/flow_prefect.py
queries_path: ../../Tables/Queries/queries.py
